# PipList = [
# 		"pip",
# 		"setuptools",
# 		"shortuuid",
# 		"simplejson",
# 		"cffi",
# 		"cryptography",
# 		"pysftp",
# 		"xmltodict",
# 		"tendo",
# 		"xlwt",
# 		"pypdf2",
# 		"simple-crypt",
# 		"wavefile",
# 		"pypdf2",
# 		"pysoundfile",
# 		"weasyprint",
# 		"dicttoxml",
# 		"requests",
# 		"lxml",
# 		"rpy2==2.8.4",
# 		"pandas",
# 		"supervisor",
# 		"requests-toolbelt",
# 		"wstools",
# 		"future",
# 		"Pillow",
# 		"netifaces",
# 		"pylru",
# 		"GitPython",
# 		"lru",
# 		"click",
# 		"py_lru_cache",
# 		"setuptools",
# 		"sqlescapy",
# 		"pyfiglet",
# 		"psutil",
# 		"mysqlclient",
# 		"configparser",
# 		"redis"
# 	]

PipList = [
	"Pandas",
	# "click",
	# "sqlescapy",
	# "wstools"
]